lectures/lecture3/hello/urls.py
from django.urls import path
from . import views

app_name = 'Hello'
urlpatterns = [
    path("", views.index, name="Index"),
    path("<str:name>", views.greet, name="greet"),
    path("hermione", views.hermione, name="hermione"),
]

lectures/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

lectures/lecture3/newyear/urls.py
from django.urls import path
from . import views

app_name = 'newyear'
urlpatterns = [
    path("", views.index, name="Index")
]

lectures/lecture3/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path("", views.index, name="Index"),
    path("add", views.add, name="Add"),
]

lectures/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "hello/index.html")


def hermione(request):
    return HttpResponse("Hello, noob")


def greet(request, name):
    # return HttpResponse(f"Hello, {name.capitalize()}!")
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

lectures/lecture3/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.


def index(request):
    now = datetime.datetime.now()

    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1,
    })

lectures/lecture3/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:Index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form,
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm(),
    })

lectures/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, {{ name }}</h1>
</body>
</html>

lectures/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, world!</h1>
</body>
</html>

lectures/lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Is it New Year's</title>
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
    <a href="{% url 'newyear:Index' %}"></a>
</body>
</html>

lectures/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:Add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:Index' %}">View tasks</a>
{% endblock %}

lectures/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:Add' %}">Add a new task</a>
{% endblock %}

lectures/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>